package trabalhopoo;

/**
 *
 * @author Pedro Ariel
 */
public class TelaSobre extends javax.swing.JFrame {

    /**
     * Creates new form Tela1
     */
    public TelaSobre() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("O show do Pedrão é um jogo de perguntas e respostas.");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(300, 70, 370, 14);

        jLabel2.setText("O jogador deve responder à uma pergunta por rodada e, caso ele responda corretamente, ganha um ponto.");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(170, 110, 620, 14);

        jLabel3.setText("Ao final, o score do jogador será gravado em um arquivo em seu computador para ser visualizado na Tabela de Classificação.");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(130, 170, 720, 30);

        jLabel4.setText("Jogo criado para fins acadêmicos.");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(350, 220, 330, 14);

        jLabel6.setText("Caso o jogador não responda corretamente, o jogo não será finalizado, porém, ele não receberá um ponto.");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(180, 140, 650, 14);

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(410, 250, 61, 23);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalhopoo/Imagens/sobre.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 890, 360);

        setSize(new java.awt.Dimension(891, 387));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new TelaPrincipal().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
